<?{

	$ASSIGNMENTS_TABLE = XOOPS_DB_PREFIX.'_' . 'tsx_assignments';
	$CLIENT_TABLE = XOOPS_DB_PREFIX.'_' . 'tsx_client';
	$CONFIG_TABLE = XOOPS_DB_PREFIX.'_' . 'tsx_config';
	$NOTE_TABLE = XOOPS_DB_PREFIX.'_' . 'tsx_note';
	$PROJECT_TABLE = XOOPS_DB_PREFIX.'_' . 'tsx_project';
	$TASK_TABLE = XOOPS_DB_PREFIX.'_' . 'tsx_task';
	$TASK_ASSIGNMENTS_TABLE = XOOPS_DB_PREFIX.'_' . 'tsx_task_assignments';
	$TIMES_TABLE = XOOPS_DB_PREFIX.'_' . 'tsx_times';
	$USER_TABLE = XOOPS_DB_PREFIX.'_' . 'tsx_user';
	$XOOPS_USER_TABLE = XOOPS_DB_PREFIX.'_' . 'users';

}
