<?php
$modversion['name'] = 'timesheetXoops';
$modversion['version'] = '1.23';
$modversion['description'] = 'timesheetXoops';
$modversion['author'] = 'http://www.advancen.com/timesheet/';
$modversion['credits'] = 'Sqeezed into XOOPS and enhanced by Duncan Keir based on timesheet.php 1.2.1 by advancen.com ';
$modversion['help'] = '';
$modversion['license'] = 'GPL';
$modversion['official'] = 1;
$modversion['image'] = 'tsx_logo.jpg';
$modversion['dirname'] = 'timesheetxoops';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'tsx_assignments';
$modversion['tables'][1] = 'tsx_client';
$modversion['tables'][2] = 'tsx_config';
$modversion['tables'][3] = 'tsx_note';
$modversion['tables'][4] = 'tsx_project';
$modversion['tables'][5] = 'tsx_task';
$modversion['tables'][6] = 'tsx_task_assignments';
$modversion['tables'][7] = 'tsx_times';
$modversion['tables'][8] = 'tsx_user';

// Admin things
$modversion['hasAdmin'] = 1;
//$modversion['adminindex'] = "admin/index.php";
//$modversion['adminmenu'] = "admin/menu.php";

// Menu
$modversion['hasMain'] = 1;

// Templates
$modversion['templates'][1]['file'] = 'timesheet_index.html';
$modversion['templates'][1]['description'] = '';

//Config settings
$modversion['config'][1]['name'] = 'configadmin';
$modversion['config'][1]['title'] = '_MI_TSXCONFIG_CONFIG';
$modversion['config'][1]['description'] = '_MI_TSXCONFIG_CONFIGDSC';
$modversion['config'][1]['formtype'] = 'group_multi';
$modversion['config'][1]['valuetype'] = 'array';
$modversion['config'][1]['default'] = '1 2 3';

$modversion['config'][2]['name'] = 'clientadmin';
$modversion['config'][2]['title'] = '_MI_TSXCONFIG_CLIENT';
$modversion['config'][2]['description'] = '_MI_TSXCONFIG_CLIENTDSC';
$modversion['config'][2]['formtype'] = 'group_multi';
$modversion['config'][2]['valuetype'] = 'array';
$modversion['config'][2]['default'] = '1 2 3';

$modversion['config'][3]['name'] = 'projectadmin';
$modversion['config'][3]['title'] = '_MI_TSXCONFIG_PROJECT';
$modversion['config'][3]['description'] = '_MI_TSXCONFIG_PROJECTDSC';
$modversion['config'][3]['formtype'] = 'group_multi';
$modversion['config'][3]['valuetype'] = 'array';
$modversion['config'][3]['default'] = '1 2 3';

$modversion['config'][4]['name'] = 'taskadmin';
$modversion['config'][4]['title'] = '_MI_TSXCONFIG_TASK';
$modversion['config'][4]['description'] = '_MI_TSXCONFIG_TASKDSC';
$modversion['config'][4]['formtype'] = 'group_multi';
$modversion['config'][4]['valuetype'] = 'array';
$modversion['config'][4]['default'] = '1 2 3';

$modversion['config'][5]['name'] = 'useradmin';
$modversion['config'][5]['title'] = '_MI_TSXCONFIG_USER';
$modversion['config'][5]['description'] = '_MI_TSXCONFIG_USERDSC';
$modversion['config'][5]['formtype'] = 'group_multi';
$modversion['config'][5]['valuetype'] = 'array';
$modversion['config'][5]['default'] = '1 2 3';

$modversion['config'][6]['name'] = 'report';
$modversion['config'][6]['title'] = '_MI_TSXCONFIG_REPORT';
$modversion['config'][6]['description'] = '_MI_TSXCONFIG_REPORTDSC';
$modversion['config'][6]['formtype'] = 'group_multi';
$modversion['config'][6]['valuetype'] = 'array';
$modversion['config'][6]['default'] = '1 2 3';
